// MODIFICA ESTA URL POR LA DEL SERVICIO WEB DESPUES DE HABERLO DESPLEGADO
const AS_URL_BASE = "https://script.google.com/macros/s/AKfycbx4jMyZ9kfZkHDMjljjNRGThSG6sEORjVx4h3eEsKZQLWHjxrRAE4FpgYgVC9E3Nbi-Nw/exec";
